version: "3.8"
services:
  #Laravel Service
  ct_app:
    container_name: ct_app
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=laravel_react_app"
    volumes:
      - .:/var/www/app
    # depends_on:
    #   - mt_database
    # links:
    #   - mt_database
    networks:
      - ct_network

  #DB Service
  # mt_database:
  #   image: mariadb:latest
  #   container_name: mt_database
  #   restart: always
  #   working_dir: /etc/mysql
  #   tty: true
  #   environment:
  #     MYSQL_DATABASE: soat_maintain
  #     MYSQL_USER: maintain
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_PASSWORD: admin
  #   ports:
  #     - 3333:3306
  #   volumes:
  #     - ./.docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - mt_network

  #Nginx Service
  ct_network:
    image: nginx:alpine
    container_name: ct_network
    restart: always
    tty: true
    ports:
      - 8200:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - ct_app
    networks:
      - ct_network

#Docker Networks
networks:
  ct_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
